import {
  LmAccordion,
  LmAvatar,
  LmButton,
  LmButtonList,
  LmCardList,
  LmCategoryBox,
  LmDateHeadline,
  LmDivider,
  LmFlexRow,
  LmGridColumn,
  LmGridRow,
  LmHeadline,
  LmHtml,
  LmHubspotMeeting,
  LmIcon,
  LmIframe,
  LmIframeAdvanced,
  LmImage,
  LmImageList,
  LmLink,
  LmListSearchAutocomplete,
  LmListSearchField,
  LmListWidget,
  LmMenu,
  LmMotion,
  LmNavList,
  LmPage,
  LmRichTextParagraph,

  LmSectionParallax,
  LmSectionVideo,
  LmSlider,
  LmStaticContainer,
  LmStaticSection,
  LmTable,
  LmTabs,
  LmTimeline,
  LmParagraph, LmSection
} from '../index'


// import HubspotForm from './hubspot/HubspotForm'
// import Form from './form/Form'
// import Pricing from './pricing/Pricing'
// import Promotion from './promotion/Promotion'

const Components = {
  'page': LmPage,
  'table': LmTable,
  'accordion': LmAccordion,
  // 'promotion': Promotion,
  'static_section': LmStaticSection,
  'static_container': LmStaticContainer,
  'divider': LmDivider,
  'html': LmHtml,
  // 'pricing': Pricing,
  // 'hubspot_form': HubspotForm,
  'hubspot_meeting': LmHubspotMeeting,
  'button_list': LmButtonList,
  'section': LmSection,
  'headline': LmHeadline,
  'paragraph': LmParagraph,
  'row': LmGridRow,
  'column': LmGridColumn,
  'image': LmImage,
  'image_list': LmImageList,
  'button': LmButton,
  'nav_list': LmNavList,
  'nav_menu': LmMenu,
  'icon': LmIcon,
  'iframe': LmIframe,
  'slider': LmSlider,
  'section_video_bg': LmSectionVideo,
  'card_list': LmCardList,
  'section_parallax': LmSectionParallax,
  // 'form': Form,
  'tabs': LmTabs,
  'list_widget': LmListWidget,
  'flex_row': LmFlexRow,
  'iframe_advanced': LmIframeAdvanced,
  'category_box': LmCategoryBox,
  'list_search_field': LmListSearchField,
  'link': LmLink,
  'list_search_autocomplete': LmListSearchAutocomplete,
  'rich_text_editor': LmRichTextParagraph,
  'timeline': LmTimeline,
  'avatar': LmAvatar,
  'date_headline': LmDateHeadline,
  'motion': LmMotion
}

export default Components
